minWorkers: 1
maxWorkers: 1
maxBatchDelay: 100
responseTimeout: 10800
batchSize: 1

handler:
    model_checkpoint_dir: "Mistral-7B-Instruct-v0.1-split"
    model_compiled_weights: "neuronx_artifacts"
    amp: "bf16"
    tp_degree: 2
    n_positions: 256
    top_k: 50
    top_p: 0.9
    temperature: 0.9

micro_batching:
    micro_batch_size: 1 
    parallelism:
        preprocess: 2
        inference: 1
        postprocess: 2